import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const HEAD = [
  ['<html lang="ar" dir="rtl">', '<html lang="en" dir="ltr">'],
  ["bootstrap.rtl.min.css", "bootstrap.min.css"],
  ["<!-- Bootstrap 5 RTL CSS -->", "<!-- Bootstrap 5 LTR CSS -->"],
];

const HREF_SKIP = new Set([
  "support.html",
  "smart-proposal-generator.html",
  "smart-proposal-template.html",
  "smart-proposal-export.html",
]);

function ltrifyHrefs(content) {
  return content.replace(/href="([a-zA-Z0-9_-]+)\.html([^"]*)"/g, (full, page, rest) => {
    if (page.endsWith("-ltr")) return full;
    if (page === "support") return `href="support-ltr.html${rest}"`;
    return `href="${page}-ltr.html${rest}"`;
  });
}

function fixLangSwitch(content, arabicPage) {
  return content
    .replace(
      /href="(?:support-ltr|smart-proposal-(?:generator|template|export)(?:-ltr)?)\.html" class="nav-link"(?=[\s\S]*?<span>(?:English|العربية)<\/span>)/,
      `href="${arabicPage}" class="nav-link"`
    )
    .replace(/<span>English<\/span>/, "<span>العربية</span>");
}

/** Longest-first string replacements for SPG + shared dashboard copy */
const REPLACEMENTS = [
  ["تصدير العرض | مولد العروض الذكي", "Export Proposal | Smart Proposal Generator"],
  ["اختر قالب تصميم العرض | مولد العروض الذكي", "Choose Proposal Template | Smart Proposal Generator"],
  ["مولد العروض الذكي | ترشيحات", "Smart Proposal Generator | Trsyat"],
  ["title>مولد العروض الذكي", "title>Smart Proposal Generator"],
  ["href=\"smart-proposal-template.html\"", "href=\"smart-proposal-template-ltr.html\""],
  ["href=\"smart-proposal-export.html\"", "href=\"smart-proposal-export-ltr.html\""],
  ["href=\"smart-proposal-generator.html#spg-content-review\"", "href=\"smart-proposal-generator-ltr.html#spg-content-review\""],
  ["action=\"smart-proposal-export.html\"", "action=\"smart-proposal-export-ltr.html\""],
  ["aria-label=\"مراحل إعداد العرض\"", "aria-label=\"Proposal preparation steps\""],
  ["مراجعة المحتوى", "Content review"],
  ["اختيار القالب", "Choose template"],
  ["التصدير", "Export"],
  ["المشروع الحالي", "Current project"],
  ["تأهيل الأسوار الخرسانية", "Concrete Fence Qualification"],
  ["إنتاج العرض", "Proposal production"],
  ["اختر قالب تصميم العرض", "Choose a proposal design template"],
  ["حدد الشكل والتصميم البصري الذي يناسب عرضك.", "Pick the visual style that fits your proposal."],
  ['aria-label="قوالب تصميم العرض"', 'aria-label="Proposal design templates"'],
  ["معاينة القالب الاحترافي", "Professional template preview"],
  ["معاينة القالب العصري", "Modern template preview"],
  ["معاينة القالب المبسط", "Minimal template preview"],
  ["معاينة القالب الفاخر", "Luxury template preview"],
  ["معاينة القالب المرئي", "Visual template preview"],
  ["احترافي", "Professional"],
  ["الأكثر طلبًا", "Most popular"],
  ["تصميم رسمي ومتوازن يناسب العروض الحكومية والتجارية.", "A formal, balanced layout for government and commercial proposals."],
  ["عصري", "Modern"],
  ["جديد", "New"],
  ["خطوط واضحة وتنسيق معاصر يبرز التفاصيل بطريقة أنيقة.", "Clean typography and contemporary layout that highlights details elegantly."],
  ["مبسط", "Minimal"],
  ["تصميم هادئ ومنظم يركز على وضوح المحتوى وسهولة القراءة.", "A calm, organized design focused on clarity and readability."],
  ["فاخر", "Luxury"],
  ["مميز", "Premium"],
  ["تصميم راقٍ بتفاصيل بصرية مميزة يناسب العروض عالية المستوى.", "A refined design with distinctive visuals for high-stakes proposals."],
  ["مرئي", "Visual"],
  ["إبداع", "Creative"],
  ["تصميم بصري غني يساعد على إبراز المعلومات والمراحل\n                        والبيانات بطريقة جذابة.", "A rich visual layout that highlights information, phases, and data attractively."],
  ["تصميم بصري غني يساعد على إبراز المعلومات والمراحل والبيانات بطريقة جذابة.", "A rich visual layout that highlights information, phases, and data attractively."],
  ["معاينة", "Preview"],
  ["اختر هذا القالب", "Select this template"],
  ["اختر هذا\n            القالب", "Select this template"],
  ["مختار حاليًا", "Currently selected"],
  ["متابعة لتصدير العرض", "Continue to export"],
  ["معاينة: عصري", "Preview: Modern"],
  ["خطوط واضحة وتنسيق معاصر يبرز التفاصيل بطريقة أنيقة.", "Clean typography and contemporary layout that highlights details elegantly."],
  ["aria-label=\"إغلاق\"", "aria-label=\"Close\""],
  ["معاينة القالب الاحترافي لتصميم العرض الفني", "Professional technical proposal template preview"],
  ["تصميم احترافي وتقدر تعدل عليه بسهولة", "Professional design you can customize easily"],
  ["يدعم اللغة العربية بالكامل من اليمين لليسار", "Full Arabic RTL support"],
  ["تصدير بصيغة PDF بجودة عالية", "High-quality PDF export"],
  ["متوافق ومتناسق مع جميع الأجهزة والشاشات", "Responsive across devices and screen sizes"],
  ["تصدير العرض", "Export proposal"],
  ["رجوع لاختيار القالب", "Back to template selection"],
  ["فيديو شرح", "How-to video"],
  ["مولد العروض الذكي", "Smart Proposal Generator"],
  ["توليد العروض الفنية والمالية بالذكاء الاصطناعي", "Generate technical and financial proposals with AI"],
  ["أنشئ عرضًا متكاملًا عبر معالج تفاعلي خطوة بخطوة — من بيانات المناقصة إلى مراجعة أقسام العرض قبل\n                  توليد المحتوى.", "Build a complete proposal through an interactive step-by-step wizard—from tender details to section review before content generation."],
  ["أنشئ عرضًا متكاملًا عبر معالج تفاعلي خطوة بخطوة — من بيانات المناقصة إلى مراجعة أقسام العرض قبل توليد المحتوى.", "Build a complete proposal through an interactive step-by-step wizard—from tender details to section review before content generation."],
  ["كيف يمكننا مساعدتك اليوم؟", "How can we help you today?"],
  ["إنشاء عرض فني ومالي لمناقصة حكومية", "Create a technical and financial proposal for a government tender"],
  ["توليد عرض متكامل فني ومالي لمناقصة حكومية عبر معالج تفاعلي خطوة بخطوة.", "Generate a full technical and financial government tender proposal through an interactive wizard."],
  ["إنشاء عرض فني ومالي لمشروع خاص", "Create a technical and financial proposal for a private project"],
  ["جهّز عرضًا فنيًا وماليًا لمشروعك الخاص بإرشاد واضح في كل خطوة من المعالج.", "Prepare a technical and financial proposal for your private project with clear guidance at each wizard step."],
  ["جاهز كراسة الشروط والمواصفات للمشروع", "Tender booklet ready for the project"],
  ["قريبًا", "Coming soon"],
  ["رفع كراسة الشروط وتوليد العرض تلقائيًا — قيد التطوير.", "Upload the tender booklet and auto-generate the proposal—in development."],
  ["العودة للبداية", "Back to start"],
  ["الخطوة 1 من 5", "Step 1 of 5"],
  ["بيانات المناقصة / المشروع", "Tender / project details"],
  ["أدخل اسم المناقصة أو المشروع ورقم المناقصة لربط العرض بالمنافسة\n                    الصحيحة.", "Enter the tender or project name and tender number to link the proposal to the correct competition."],
  ["أدخل اسم المناقصة أو المشروع ورقم المناقصة لربط العرض بالمنافسة الصحيحة.", "Enter the tender or project name and tender number to link the proposal to the correct competition."],
  ["اسم المناقصة / المشروع", "Tender / project name"],
  ["مثال: توريد وتركيب أنظمة", "e.g. Supply and install systems"],
  ["رقم المناقصة", "Tender number"],
  ["هل لديك مستندات للمناقصة؟", "Do you have tender documents?"],
  ['<label class="form-check-label" for="spgHasDocsYes">نعم</label>', '<label class="form-check-label" for="spgHasDocsYes">Yes</label>'],
  ['<label class="form-check-label" for="spgHasDocsNo">لا</label>', '<label class="form-check-label" for="spgHasDocsNo">No</label>'],
  ['<label class="form-check-label" for="spgHasTeamYes">نعم</label>', '<label class="form-check-label" for="spgHasTeamYes">Yes</label>'],
  ['<label class="form-check-label" for="spgHasTeamNo">لا</label>', '<label class="form-check-label" for="spgHasTeamNo">No</label>'],
  ['<label class="form-check-label" for="spgHasContractsYes">نعم</label>', '<label class="form-check-label" for="spgHasContractsYes">Yes</label>'],
  ['<label class="form-check-label" for="spgHasContractsNo">لا</label>', '<label class="form-check-label" for="spgHasContractsNo">No</label>'],
  ["مستندات المناقصة", "Tender documents"],
  ["أدخل بيانات المستند ثم ارفع الملف.", "Enter document details, then upload the file."],
  ["اسم الملف", "File name"],
  ["وصف الملف", "File description"],
  ["وصف مختصر", "Short description"],
  ["الملف", "File"],
  ["اسحب الملف هنا أو تصفح لإضافته للقائمة", "Drag a file here or browse to add it to the list"],
  ["أقصى حجم 500 ميغابايت", "Max size 500 MB"],
  ["تعديل مستند محفوظ", "Editing saved document"],
  ["حفظ التعديل", "Save changes"],
  ["الوصف", "Description"],
  ["الإجراءات", "Actions"],
  ["عرض المزيد", "View more"],
  ['aria-label="تعديل"', 'aria-label="Edit"'],
  ['aria-label="حذف"', 'aria-label="Delete"'],
  [">تعديل</button>", ">Edit</button>"],
  [">حذف</button>", ">Delete</button>"],
  [">إلغاء</button>", ">Cancel</button>"],
  [">Close</button>", ">Close</button>"],
  ["كراسة الشروط والمواصفات", "Terms and specifications booklet"],
  ["كراسة الشروط الفنية والإدارية للمنافسة بما يشمل نطاق العمل ومعايير التقييم.", "Technical and administrative tender booklet including scope of work and evaluation criteria."],
  ["جدول الكميات", "Bill of quantities"],
  ["بنود الأعمال والكميات التقديرية للمشروع.", "Work items and estimated quantities for the project."],
  ["المخططات الهندسية المعتمدة", "Approved engineering drawings"],
  ["المخططات المعمارية والكهربائية المعتمدة من الجهة\n                                  المالكة.", "Approved architectural and electrical drawings from the owner."],
  ["المخططات المعمارية والكهربائية المعتمدة من الجهة المالكة.", "Approved architectural and electrical drawings from the owner."],
  ["هل لديك فريق عمل جاهز بأسماء وسير ذاتية لإضافتهم في العرض؟", "Do you have a team ready with names and CVs to include in the proposal?"],
  ["أعضاء فريق العمل", "Team members"],
  ["أكمل بيانات العضو ثم احفظها. يمكنك إضافة عدة أعضاء.", "Complete member details and save. You can add multiple members."],
  ["اسم الموظف", "Employee name"],
  ["الجنسية", "Nationality"],
  ["اختر الجنسية", "Select nationality"],
  ["سعودي", "Saudi"],
  ["سعودية", "Saudi"],
  ["غير سعودي", "Non-Saudi"],
  ["المسمى الوظيفي", "Job title"],
  ["الشهادة", "Degree"],
  ["سنوات الخبرة", "Years of experience"],
  ["اختر سنوات الخبرة", "Select years of experience"],
  ["ملف السيرة الذاتية", "CV file"],
  ["القدرات والملخص", "Skills and summary"],
  ["اكتب القدرات والملخص", "Describe skills and summary"],
  ["حفظ وإضافة\n                          للقائمة", "Save and add to list"],
  ["حفظ وإضافة للقائمة", "Save and add to list"],
  ["تعديل عضو محفوظ", "Editing saved member"],
  ["المؤهل", "Qualification"],
  ["12 سنة", "12 years"],
  ["8 سنوات", "8 years"],
  ["6 سنوات", "6 years"],
  ["مدير مشروع", "Project manager"],
  ["مهندسة نظم", "Systems engineer"],
  ["محاسب تكاليف", "Cost accountant"],
  ["بكالوريوس هندسة مدنية", "B.Sc. Civil Engineering"],
  ["ماجستير علوم الحاسب", "M.Sc. Computer Science"],
  ["بكالوريوس محاسبة", "B.Sc. Accounting"],
  ["أحمد محمد علي", "Ahmed Mohammed Ali"],
  ["سارة خالد العتيبي", "Sara Khalid Al-Otaibi"],
  ["فهد عبدالرحمن القحطاني", "Fahad Abdulrahman Al-Qahtani"],
  ["المشاريع السابقة", "Past projects"],
  ["إضافة مشروع", "Add project"],
  ["aria-label=\"اختيار المشروع\"", 'aria-label="Select project"'],
  ["aria-label=\"إغلاق قائمة المشاريع\"", 'aria-label="Close project list"'],
  ["البحث في المشاريع", "Search projects"],
  ['aria-label="قائمة المشاريع"', 'aria-label="Project list"'],
  [" وصف المشروع", " Project description"],
  ["خدمات المناسبات", "Event services"],
  ["لا توجد مشاريع بعد. ابدأ بإضافة مشروع جديد.", "No projects yet. Start by adding a new project."],
  ["الإشعارات", "Notifications"],
  ["ابقي علي الأطلاع بالإشعارات", "Stay updated with notifications"],
  ["قراءة الكل", "Read All"],
  ["الكل", "All"],
  ["غير مقروءة (12)", "Unread (12)"],
  ["البحث في الداشبورد", "Search in Dashboard"],
  ["الرئيسية", "Home"],
  ["المناقصات", "Tenders"],
  ["مناقصات ترشيحات", "Trsyat tenders"],
  ["المناقصات التقديرية", "Estimated tenders"],
  ["مناقصات الفرصة", "Forsa tenders"],
  ["المناقصات المرشحة", "Nominated tenders"],
  ["العروض والاستشارات", "Proposals & consultations"],
  ["نتائج المناقصات", "Tender results"],
  ["إعلان المناقصة", "Tender announcement"],
  ["تسعير المناقصات", "Tender pricing"],
  ["إدارة المناقصات", "Tenders management"],
  ["الدعم الفني", "Support"],
  ["Upgrade الحساب", "Upgrade account"],
  ["Support الفني", "Support"],
  ["ترقية", "Upgrade"],
  ["الملف الشخصي", "Profile"],
  ["الإعدادات", "Settings"],
  ["تسجيل الخروج", "Log out"],
  ["دليل الاستخدام", "User guide"],
  ["متابعة لاختيار القالب", "Continue to choose template"],
  ["رجوع", "Back"],
  ["التفاصيل", "Details"],
  ["عرض التفاصيل الكاملة", "View full details"],
  ["محتوى التفاصيل يُعرض هنا من الخادم.", "Detail content is loaded here from the server."],
  ["<title>مولد العروض الذكي</title>", "<title>Smart Proposal Generator</title>"],
  ["هل لديك عقود سابقة؟", "Do you have past contracts?"],
  ["العقود والمشاريع السابقة", "Past contracts and projects"],
  ["أدخل بيانات المشروع أو العقد ثم احفظها.", "Enter project or contract details, then save."],
  ["اسم المشروع", "Project name"],
  ["الجهة", "Entity"],
  ["وصف المشروع", "Project description"],
  ["سنة المشروع", "Project year"],
  ["مدة المشروع", "Project duration"],
  ["تكلفة المشروع", "Project cost"],
  ["اسم ملف العقد", "Contract file name"],
  ["حفظ\n                          وإضافة للقائمة", "Save and add to list"],
  ["حفظ وإضافة للقائمة", "Save and add to list"],
  ["تعديل عقد/مشروع محفوظ", "Editing saved contract/project"],
  ["السنة", "Year"],
  ["المدة", "Duration"],
  ["التكلفة", "Cost"],
  ["12 شهر", "12 months"],
  ["24 شهر", "24 months"],
  ["9 أشهر", "9 months"],
  ["ريال", "SAR"],
  ["تطوير أنظمة الموارد البشرية", "HR systems development"],
  ["وزارة الموارد البشرية", "Ministry of Human Resources"],
  ["توريد وتنفيذ منظومة إلكترونية لإدارة الموارد البشرية مع التدريب والدعم الفني.", "Supply and implement an electronic HR management system with training and technical support."],
  ["صيانة وتشغيل مراكز البيانات", "Data center operations and maintenance"],
  ["هيئة الحكومة الرقمية", "Digital Government Authority"],
  ["عقد تشغيل وصيانة لمراكز البيانات يشمل المراقبة على مدار الساعة وخطط الاستجابة\n                                    للحوادث.", "Operations and maintenance contract for data centers including 24/7 monitoring and incident response plans."],
  ["عقد تشغيل وصيانة لمراكز البيانات يشمل المراقبة على مدار الساعة وخطط الاستجابة للحوادث.", "Operations and maintenance contract for data centers including 24/7 monitoring and incident response plans."],
  ["توريد أجهزة شبكات الاتصال", "Network equipment supply"],
  ["أمانة منطقة الرياض", "Riyadh Region Municipality"],
  ["توريد وتركيب أجهزة شبكات الاتصال لمباني الأمانة مع الضمان\n                                  والصيانة.", "Supply and install network equipment for municipality buildings with warranty and maintenance."],
  ["توريد وتركيب أجهزة شبكات الاتصال لمباني الأمانة مع الضمان والصيانة.", "Supply and install network equipment for municipality buildings with warranty and maintenance."],
  ["اختر مستوى التفصيل المناسب لحجم العرض والوقت المتاح لديك.", "Choose a detail level that fits your proposal size and available time."],
  ["مفصل", "Detailed"],
  ["عرض شامل بأقصى عمق وتوثيق لكل قسم.", "Comprehensive proposal with maximum depth and documentation for each section."],
  ["متوسط", "Medium"],
  ["توازن بين التفصيل والاختصار للمعظم.", "A balance of detail and brevity for most cases."],
  ["مختصر", "Brief"],
  ["محتوى مركز يركز على النقاط الجوهرية.", "Focused content highlighting essential points."],
  ["العقود السابقة", "Past contracts"],
  ["مستوى التفصيل", "Detail level"],
  ["التالي", "Next"],
  ["مراجعة وتأكيد أقسام العرض", "Review and confirm proposal sections"],
  ["راجع الأقسام التي اقترحها الذكاء الاصطناعي وعدّلها قبل أن نجهز لك\n                  المحتوى.", "Review AI-suggested sections and edit them before we prepare your content."],
  ["راجع الأقسام التي اقترحها الذكاء الاصطناعي وعدّلها قبل أن نجهز لك المحتوى.", "Review AI-suggested sections and edit them before we prepare your content."],
  ["إجمالي الأقسام", "Total sections"],
  ["الأقسام الأساسية", "Core sections"],
  ["الأقسام الاختيارية", "Optional sections"],
  ["الصفحات التقديرية", "Estimated pages"],
  ["حجم العرض المتوقع", "Expected proposal size"],
  ["الغلاف والمعلومات\n                          العامة", "Cover and general information"],
  ["الغلاف والمعلومات العامة", "Cover and general information"],
  ["أساسي", "Core"],
  ["بيانات المنافسة، رقم المنافسة، الجهة، الموعد النهائي", "Competition details, reference number, entity, deadline"],
  ["فهم المشروع\n                          والمنهجية", "Project understanding and methodology"],
  ["فهم المشروع والمنهجية", "Project understanding and methodology"],
  ["تحليل متطلبات المشروع، خطة العمل المعتمدة", "Requirements analysis and approved work plan"],
  ["خطة العمل\n                          والتنفيذ", "Work plan and execution"],
  ["خطة العمل والتنفيذ", "Work plan and execution"],
  ["مراحل التنفيذ، الجداول الزمنية لكل خطوة", "Execution phases and timelines for each step"],
  ["الهيكل التنظيمي وفريق\n                          العمل", "Organization structure and team"],
  ["الهيكل التنظيمي وفريق العمل", "Organization structure and team"],
  ["أدوار ومسؤوليات فريق العمل، خبرات فريق العمل", "Team roles, responsibilities, and experience"],
  ["العرض المالي", "Financial proposal"],
  ["تفاصيل التسعير، المبلغ الإجمالي شامل الضريبة", "Pricing details and total amount including tax"],
  ["الأقسام المقترحة", "Suggested sections"],
  ["خطة إدارة المخاطر", "Risk management plan"],
  ["مقترح", "Suggested"],
  ["إدارة المخاطر المحتملة وخطط الاستجابة لها", "Managing potential risks and response plans"],
  ["الخبرات والعقود\n                          السابقة", "Past experience and contracts"],
  ["الخبرات والعقود السابقة", "Past experience and contracts"],
  ["مشاريع سابقة تُظهر الخبرة والقدرات", "Past projects demonstrating experience and capabilities"],
  ["خطة إدارة الجودة", "Quality management plan"],
  ["معايير الجودة، طرق المراجعة، التوثيق", "Quality standards, review methods, documentation"],
  ["الجدول الزمني\n                          للتنفيذ", "Implementation timeline"],
  ["الجدول الزمني للتنفيذ", "Implementation timeline"],
  ["المراحل، المخرجات، المسؤولون", "Phases, deliverables, owners"],
  ["تأكيد والمتابعة\n                  للمراجعة", "Confirm and continue to review"],
  ["تأكيد والمتابعة للمراجعة", "Confirm and continue to review"],
  ["العرض جاهز للمراجعة", "Proposal ready for review"],
  ["راجع محتوى كل قسم أدناه. تأكد من الصياغة قبل\n                          اعتماد العرض النهائي.", "Review each section below. Confirm wording before final approval."],
  ["راجع محتوى كل قسم أدناه. تأكد من الصياغة قبل اعتماد العرض النهائي.", "Review each section below. Confirm wording before final approval."],
  ["أقسام العرض", "Proposal sections"],
  ["الملخص\n                                      التنفيذي", "Executive summary"],
  ["الملخص التنفيذي", "Executive summary"],
  ["فهم\n                                      المتطلبات", "Requirements understanding"],
  ["فهم المتطلبات", "Requirements understanding"],
  ["منهجية\n                                      التنفيذ", "Implementation methodology"],
  ["منهجية التنفيذ", "Implementation methodology"],
  ["خطة\n                                      العمل", "Work plan"],
  ["خطة العمل", "Work plan"],
  ["فريق\n                                      العمل", "Team"],
  ["فريق العمل", "Team"],
  ["إجمالي الكلمات", "Total words"],
  ["سيظهر محتوى الملخص التنفيذي هنا.", "Executive summary content will appear here."],
  ["سيظهر محتوى فهم المتطلبات هنا.", "Requirements understanding content will appear here."],
  ["سيظهر محتوى منهجية التنفيذ هنا.", "Implementation methodology content will appear here."],
  ["سيظهر محتوى خطة العمل هنا.", "Work plan content will appear here."],
  ["سيظهر محتوى فريق العمل هنا.", "Team content will appear here."],
  ["سيظهر محتوى الخبرات والعقود السابقة هنا.", "Past experience and contracts content will appear here."],
  ["سيظهر محتوى العرض المالي هنا.", "Financial proposal content will appear here."],
  ["الملحقات", "Appendices"],
  ["سيظهر محتوى الملحقات هنا.", "Appendices content will appear here."],
  ["text-end", "text-start"],
];

REPLACEMENTS.sort((a, b) => b[0].length - a[0].length);

function applyReplacements(content) {
  let out = content;
  for (const [from, to] of REPLACEMENTS) {
    out = out.split(from).join(to);
  }
  return out;
}

function processFile(filename, arabicPage) {
  const filePath = path.join(root, filename);
  let content = fs.readFileSync(filePath, "utf8");
  for (const [from, to] of HEAD) {
    content = content.split(from).join(to);
  }
  content = ltrifyHrefs(content);
  content = fixLangSwitch(content, arabicPage);
  content = applyReplacements(content);
  fs.writeFileSync(filePath, content, "utf8");
  console.log("Updated", filename);
}

processFile("smart-proposal-generator-ltr.html", "smart-proposal-generator.html");
processFile("smart-proposal-template-ltr.html", "smart-proposal-template.html");
processFile("smart-proposal-export-ltr.html", "smart-proposal-export.html");
